lom/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from posts.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'posts': PostSitemap,
}



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('posts.urls', namespace='posts'), name='main-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url, include
from . import views
from .feeds import LatestPostFeed



urlpatterns = [
    url(r'^$', views.post_list, name='main-page'),
    url(r'^$', views.post_list, name='list'),
    url(r'^draft/$', views.post_draft_list, name='draft_list'),
    url(r'^feed/$', LatestPostFeed(), name='feed'),
    url(r'^search/$', views.post_search, name='search'),
    url(r'^category/$', views.list_category, name='list_category'),
    url(r'^category/create/$', views.create_category, name='create_category'),
    url(r'^category/(?P<id>\d+)/(?P<path>.*)$', views.post_category, name='category'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$', views.post_list, name='list_by_tag'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^post/(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^post/(?P<slug>[\w-]+)/edit/$', views.post_update, name='edit'),
]

posts/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify, mark_safe
from django.db.models.signals import pre_save
from django.utils import timezone

from markdown_deux import markdown
from taggit.managers import TaggableManager

from comments.models import Comment
from .utils import get_read_time
from .categoryModels import Category

# Create your models here.


class PostPublishedManager(models.Manager):
    def published(self):
        return super(PostPublishedManager, self).get_queryset().filter(status='published').filter(publish__lte=timezone.now())

    def draft(self):
        return super(PostPublishedManager, self).get_queryset().filter(Q(status='draft') | Q(publish__gte=timezone.now()))



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Roboczy'),
        ('published', 'Opublikowany'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, max_length=191)
    author = models.ForeignKey(User, related_name='blog_posts')
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.ForeignKey('posts.Category')

    tags = TaggableManager()
    objects = PostPublishedManager()


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail',
                       args=[self.slug])

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from posts.categoryModels import Category
from .models import Post
from pagedown.widgets import PagedownWidget


class SearchForm(forms.Form):
    query = forms.CharField()


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "parent",
            "name",
        ]


class PostForm(forms.ModelForm):
    DATEPICKER = {
        'type': "text",
    }
    help_text = '<a href="http://pygments.org/docs/lexers/">Language syntax</a>, <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown cheatsheet</a>'
    content = forms.CharField(widget=PagedownWidget(show_preview=False), help_text=help_text)
    publish = forms.DateTimeField(widget=forms.widgets.Input(attrs=DATEPICKER))

    def __init__(self, *args, publish_disabled=False, **kwargs ):
        super(PostForm, self).__init__(*args, **kwargs)

        if publish_disabled:
            self.fields['publish'].widget.attrs['readonly'] = True


    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "status",
            "publish",
            "category",
            "tags",
        ]

posts/views.py
from itertools import chain

from django.conf import settings
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.db.models import F
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mail
from haystack.management.commands import update_index

from comments.forms import CommentForm
from comments.models import Comment
from posts.utils import deep_search_category
from .models import Post
from .categoryModels import Category

from haystack.query import SearchQuerySet

from .forms import PostForm, SearchForm, CategoryForm
from taggit.models import Tag


# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.objects.published()
    if request.GET.get('last_update') != None:
        if request.user.is_active and request.user.is_authenticated():
            object_list = Post.objects.published()\
                .exclude(updated__lte=F('timestamp')).filter(updated__gte=request.user.last_login)
            # user = request.user
            # timezone = user.last_login.tzinfo
            # user.last_login = datetime.now(tz=timezone)
            # user.save()
    if request.GET.get('news') != None:
        if request.user.is_active and request.user.is_authenticated():
            object_list = Post.objects.published().filter(publish__gte=request.user.last_login)

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # Pagination
    paginator = Paginator(object_list, settings.POST_PER_PAGE)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'page': posts,
        'tag': tag,
    }
    return render(request, 'post/list.html', context)


def post_draft_list(request):
    if not request.user.is_active:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    object_list = Post.objects.draft().filter(author=request.user)

    # Pagination
    paginator = Paginator(object_list, settings.POST_PER_PAGE)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'page': posts,
    }
    return render(request, 'post/draft_list.html', context)


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.status == 'draft':
        if request.user != post.author:
            raise Http404

    # list similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.published().filter(tags__in=post_tags_ids)\
                                            .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    initial_data = {
        "content_type": post.get_content_type,
        "object_id": post.id
    }

    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated():
        c_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        content_data = comment_form.cleaned_data.get('content')
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()


        new_comment, created = Comment.objects.get_or_create(
                                                user=request.user,
                                                content_type=content_type,
                                                object_id=obj_id,
                                                content=content_data,
                                                parent=parent_obj,
                                            )
        try:
            send_mail('[LOM] Add comment to {} by '.format(post.title, request.user),
                      "Hi {},\nuser '{}' add below comment to you posts\nComment:\n{}".format(post.author, request.user, content_data), 
                      'lomweb@lomweb.com', [post.author.email], fail_silently=False)
        except Exception as e:
            print("exception", str(e))   
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = post.comments
    context = {
        'post': post,
        'similar_posts': similar_posts,
        "comments": comments,
        "comment_form": comment_form,
    }

    return render(request, 'post/detail.html', context)


def post_create(request):
    if not request.user.is_active:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404
    form = PostForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        date_now = timezone.now()
        if (date_now - instance.publish ).total_seconds() > 60:
            instance.publish = date_now
        instance.save()
        form.save_m2m()
        messages.success(request, "Saved")
        # update solr indexing
        update_index.Command().handle()
        if instance.status == "draft":
            return HttpResponseRedirect(reverse('posts:draft_list'))
        else:
            return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form": form,
    }
    return render(request, 'post/form.html', context)


def post_update(request, slug=None):
    if not request.user.is_active:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    instance = get_object_or_404(Post, slug=slug)
    publish_disabled = True if instance.status != 'draft' else False

    if instance.author != request.user:
        raise Http404

    form = PostForm(request.POST or None, instance=instance, publish_disabled=publish_disabled)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        form.save_m2m()
        messages.success(request, "Updated")
        if instance.status == "draft":
            return HttpResponseRedirect(reverse('posts:draft_list'))
        else:
            return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "form": form,
    }
    return render(request, 'post/form.html', context)


# to update the search data you need run './manage.py update_index' commend
def post_search(request):
    form = SearchForm()
    if 'query' in request.GET and request.GET.get('query') != "":
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            query = cd['query']
            search_option = request.GET.get('search_radio')
            results = SearchQuerySet().models(Post)\
                                          .filter(**{search_option: query}).load_all()

            # count whole posts
            total_results = results.count
            context = {
                'form': form,
                'cd': cd,
                'results': results,
                'total_results': total_results
            }
    else:
        context = {
            'form': form,
        }
    return render(request, 'post/search.html', context)


def post_category(request, id=None, path=None):
    category = get_object_or_404(Category, id=id)

    object_list = category.post_set.filter(status='published')

    deep_categories = deep_search_category(category)

    if request.GET.get('deep_search'):
        object_list = list(chain(*[x.post_set.filter(status='published') for x in deep_categories]))

    paginator = Paginator(object_list, settings.POST_PER_PAGE)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'category': category,
        'posts': posts,
        'page': posts
    }

    return render(request, 'post/category.html', context)


def list_category(request):
    category = Category.objects.all()
    context = {
        'category': category,
    }

    return render(request, 'category/list_category.html', context)


def create_category(request):
    if not request.user.is_active:
        raise Http404
    if not request.user.is_authenticated():
        raise Http404

    form = CategoryForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Saved category")
        return HttpResponseRedirect(reverse('posts:list'))

    context = {
        "form": form,
    }

    return render(request, 'category/create_category.html', context)

posts/templates/post/categories_link.html
{% for cat in categories %}
    <a href="{{cat.get_absolute_url }}">{{ cat.name }}</a>
    {% if not forloop.last %}
        >
    {% endif %}
{% endfor %}

posts/templates/post/category.html
{% extends 'base.html' %}
{% block title %}Category: {{ category }} {% endblock %}
{% block content %}
<div class="col-md-6">
    <h2 class="page-title">Lista postow w kategorii <span style="color: #4cae4c">"{{ category }}"</span></h2>
    <hr/>
    {% for post in posts %}
        {% include 'post/short_post.html' %}
    {% endfor %}
    {% include "pagination.html" %}
</div>
{% endblock content %}

posts/templates/post/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load post_tags %}
{% load crispy_forms_tags %}
{% block title %}Post: {{ post.title }}{% endblock %}
{% block content %}
<div class="col-md-9">
    <header class="post-title">
        {% if post.status == 'draft' %}
            <h1 style="color: darkred">Wersja robocza</h1>
        {% endif %}
        <h1 style="display: inline-block">{{ post.title }}</h1>
        {% if request.user == post.author %}
            <a href="{{ post.get_absolute_url }}edit" class="more-link" style="float: right; margin: 2em 0 0 0">Edit »</a>
        {% endif %}
    </header>
    <p class="tags">
        Tagi: {% tags_to_html_link post.tags %}
    </p>
    <p class="category">
        Category: {% categories_to_html_link post.category %}
    </p>
    <p class="category">
        Czas czytania: ~{{ post.read_time }} min
    </p>
    <div class="post-meta">
        Opublikowany {{ post.publish }} by {{ post.author }}
        {% if post.updated > post.timestamp %}
            <small><span class="post-updated">Aktualizacja: {{ post.updated|date:'d N Y H:i' }}</span></small>
        {% endif %}
    </div>
    <article>
        <div class="post-content">
            {{ post.content| markdown2 | safe }}
        </div>
    </article>
<!-- form to above author link to search all posts by author -->
    <form action="{% url 'posts:search' %}" id="author-form">
        <input type="hidden" name="query" value="{{ post.author }}">
        <input type="hidden" name="search_radio" value="author">
    </form>
<!-- end form -->
    <div>
        <p class="lead">Comments</p>
        {% if request.user.is_authenticated %}
            <form method="POST" action=".">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" value="Post comment" class="btn btn-default">
            </form>
        {% else %}
            <p>You must login to comment</p>
            <hr/>
        {% endif %}
        <hr />
        {% for comment in  comments %}
            <blockquote>
                <p>{{ comment.content }}</p>
                <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comments | {% endif %} <a class="commit-reply-btn" href="#">Reply</a> | <a href="{{ comment.get_absolute_url }}">Thread</a></footer>
                <div class="comment-replay">
                    {% for child_comment in comment.children %}
                        <blockquote>
                            <p>{{ child_comment.content }}</p>
                            <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                        </blockquote>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        <form method="POST" action=".">
                            {% csrf_token %}
                            {{ comment_form|crispy }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <input type="submit" value="Reply" class="btn btn-default">
                        </form>
                    {% else %}
                        <p>You must login to comment</p>
                        <hr/>
                    {% endif %}
                </div>
            </blockquote>
            <hr />
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block display-left-column %}

{% endblock display-left-column %}
{% block display-right-column %}
    <div class="col-md-3">
    <div class="panel-posts">
                        <div class="sidebar-module sidebar-module-inset">
                            <div class="panel-posts-title">
                                <h3>Najnowsze posty</h3>
                            </div>
                            <div class="panel-posts-body">
                                {% show_latest_posts 5 %}
                            </div>
                        </div>
                    </div>
        <div class="recent-posts">
            <div class="sidebar-module sidebar-module-inset">
                <div class="panel-posts-title">
                    <h3>Podobne posty</h3>
                </div>
                <div class="panel-posts-body">
                    <ol class="list-unstyled">
                        {% for post in similar_posts %}
                            <li class="latest-post">
                                <div>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </div>
                            </li>
                        {% empty %}
                            Nie ma podobnych postow.
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock display-right-column %}

posts/templates/post/draft_list.html
{% extends 'base.html' %}
{% load post_tags %}
{% block title %}Draft: {{ post.title }}{% endblock %}
{% block content %}
<div class="col-md-6">
    <h1 class="page-title" style="color: red">Nieopublikowane posty </h1>
    <hr/>
    {% for post in posts %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.content| markdown2 | safe |truncatewords_html:30 }}
    {% empty %}
        <p>Brak nieopublikowanych postow</p>
    {% endfor %}
    {% include "pagination.html" %}
</div>
{% endblock content %}

posts/templates/post/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
    {{ form.media }}
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
{% endblock head_extra %}
{% block title %}Add Post {% endblock %}
{% block display-left-column %}
{% endblock display-left-column %}
{% block content %}
    <div class="col-sm-6">
        <h1 class="page-title">Create Post</h1>
        <hr />
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy}}
            <input type="submit" class="btn btn-default" value="Create Post">
        </form>
    </div>
    <div class="col-sm-6">
        <h1 class="page-title">Preview</h1>
        <hr />
        <div class="content-preview">
            <h3 id="preview-title"></h3>
            <p id="preview-content"></p>
        </div>
    </div>
{% endblock content %}

{% block display-right-column %}
{% endblock display-right-column %}


{% block script_extra %}

<!-- Include Required Prerequisites -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

<!-- Include Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<script type="text/javascript">
$(function() {
    if (! $('input[name="publish"]').is('[readOnly]') ){
        $('input[name="publish"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            timePicker: true,
            timePicker24Hour: true,
            showISOWeekNumbers: true,
            showDropdowns: true,
            minDate: moment(),
            locale: {
                format: 'YYYY-MM-DD HH:mm'
            }

        });
    }
});
</script>
{% endblock script_extra %}

posts/templates/post/latest_posts.html
<ol class="list-unstyled">
    {% for post in latest_posts %}
        <li class="latest-post">
            <div>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <p>{{ post.publish|timesince }} by: {{ post.author }}</p>
            </div>
        </li>
    {% endfor %}
</ol>

posts/templates/post/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load post_tags %}
{% block title %}
    {% if tag %}
        Tag: {{ tag.name }}
    {% else %}
    List Posts
    {% endif %}
{% endblock %}
{% block content %}
<div class="col-md-6">
    {% if tag %}
        <h2 class="page-title">Posty oznaczone tagiem <span style="color: #4cae4c">"{{ tag.name }}"</span></h2>
        <hr/>
    {% endif %}
    {% for post in posts %}
        {% include 'post/short_post.html' %}
    {% endfor %}
    {% include "pagination.html" %}
</div>

{% endblock content %}

posts/templates/post/search.html
{% extends 'base.html' %}
{% block title %}Search
    {% if "query" in request.GET %}
        {{ cd.query }}
    {% endif %}
{% endblock %}
{% block content %}
<div class="col-md-6">
    {% if "query" in request.GET %}
        <h1 class="page-title">Posty zawierajace "{{ cd.query }}"</h1>
        <h3>znaleziono {{ total_results }} wynik{{ total_results|pluralize:"i" }}</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.content|truncatewords_html:10 }}
            {% endwith %}
        {% empty %}
            <p>Brak wynikow dla podanego zapytania</p>
        {% endfor %}
    {% else %}
        <h1>Szukaj postow</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Szukaj">
        </form>
    {% endif %}
</div>
{% endblock content %}

posts/templates/post/short_post.html
{% load post_tags %}
<div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
            <header class="post-header">
                <h1 class="post-title"><a href="{{ post.get_absolute_url }}" rel="bookmark">{{ post.title }} </a></h1>
                <div class="post-meta">
                    Opublikowany {{ post.publish|timesince }} by {{ post.author }}
                    {% if post.updated > post.timestamp %}
                        <small><span class="post-updated">Aktualizacja: {{ post.updated|date:'d N Y H:i' }}</span></small>
                    {% endif %}
                </div>
            </header>
            <article>
                <div class="post-content">
                    {{ post.content| markdown2 | safe |truncatewords_html:30 }}
                    <a href="{{ post.get_absolute_url }}" class="more-link">View details »</a>
                </div>
                <div class="post-tags">
                    Tagi: {% tags_to_html_link post.tags %}
                </div>
                <div class="post-category">
                    Category: {% categories_to_html_link post.category %}
                </div>
            </article>
        </div>
    </div>
</div>

posts/templates/post/tags_link.html
{% for tag in tags %}
    <a href="{% url 'posts:list_by_tag' tag.slug %}">
        {{ tag.name }}
    </a>
    {% if not forloop.last %}, {% endif %}
{% endfor %}