lom/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from posts.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'posts': PostSitemap,
}



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
    name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('posts.urls', namespace='posts'), name='main-page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url, include
from . import views
from .feeds import LatestPostFeed



urlpatterns = [
    url(r'^$', views.post_list, name='main-page'),
    url(r'^$', views.post_list, name='list'),
    url(r'^draft/$', views.post_draft_list, name='draft_list'),
    url(r'^feed/$', LatestPostFeed(), name='feed'),
    url(r'^search/$', views.post_search, name='search'),
    url(r'^category/$', views.list_category, name='list_category'),
    url(r'^category/create/$', views.create_category, name='create_category'),
    url(r'^category/(?P<id>\d+)/(?P<path>.*)$', views.post_category, name='category'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$', views.post_list, name='list_by_tag'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^post/(?P<slug>[\w-]+)/$', views.post_detail, name='detail'),
    url(r'^post/(?P<slug>[\w-]+)/edit/$', views.post_update, name='edit'),
]

templates/base.html
{% load staticfiles %}
{% load post_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>LOM | {% block title %}{% endblock %}</title>


        <link rel="stylesheet" href="{% static '/css/mtree.css'%}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link rel="stylesheet" href="{% static 'css/default.css' %}" />
        <link rel="stylesheet" href="{% static 'css/theme.css' %}" />
        <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/jquery.treemenu.css' %}" />

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{#        <!-- Optional theme -->#}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{#        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.min.css" />#}
        <link href="{% url 'posts:feed' %}" rel="alternate" title="LOM latest posts" type="application/atom+xml">

        {% block head_extra %}{% endblock head_extra %}
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'posts:main-page' %}">LOM</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li>
                    <form action="{% url 'posts:search' %}" class="navbar-form navbar-right">
                      <div class="input-group-btn form-group" >
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span id="search_type_button"></span><span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="text" checked> All</label></div></li>
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="title" >Title</label></div></li>
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="author" > Author</label></div></li>
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="category" > Category</label></div></li>
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="body" > Content</label></div></li>
                            <li><div class="radio_search"><label><input type="radio" name="search_radio" value="tags" > Tag</label></div></li>
                          <li role="separator" class="divider"></li>
                        </ul>
                        <input type="text" class="form-control" name="query" aria-label="..." placeholder="Search...">
                      </div>
                    </form>
                </li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'posts:list' %}?news=">News</a></li>
                    <li><a href="{% url 'posts:list' %}?last_update=">Last Update</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'posts:list' %}">List</a></li>
{#                        <li role="separator" class="divider"></li>#}
                        <li><a href="{% url 'posts:create' %}">Create</a></li>
{#                        <li role="separator" class="divider"></li>#}
                        <li><a href="{% url 'posts:draft_list' %}">Draft</a></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'posts:list_category' %}">List</a></li>
{#                        <li role="separator" class="divider"></li>#}
                        <li><a href="{% url 'posts:create_category' %}">Create</a></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user }}<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="{% url 'account_change_password' %}">Change password</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                      </ul>
                    </li>

                {% else %}
                    <li><a href="{% url 'account_login' %}">Login</a></li>
                    <li><a href="{% url 'account_signup' %}">Register</a></li>
{#                    <li>#}
{#                      <form class="navbar-form navbar-center" action="{% url 'account_login' %}">#}
{#                        <div class="form-group">#}
{#                          <input type="text" placeholder="Email" class="form-control">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                          <input type="password" placeholder="Password" class="form-control">#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-success">Sign in</button>#}
{#                      </form>#}
{#                    </li>#}
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        {% include "message_display.html" %}
        <div class="container">
        <div class="row">
            {% block display-left-column %}
                <div class="col-md-3">
                    {% list_category_toggle_menu %}
                </div>
            {% endblock display-left-column %}
            {% block content %}
                <div class="col-md-6">
                </div>
            {% endblock content %}

            {% block display-right-column %}
                <div class="col-md-3 ">
                    <div class="recent-posts">
                        <div class="sidebar-module sidebar-module-inset">
                            <div class="recent-posts-title">
                                <h3>Najnowsze posty</h3>
                            </div>
                            <div class="recent-posts-body">
                                {% show_latest_posts 5 %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock display-right-column %}
        </div>
        </div>


        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script
			  src="http://code.jquery.com/jquery-1.12.4.min.js"
			  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
			  crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
        <script src="{% static '/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/js/base.js' %}"></script>
        <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
        <script src="{% static 'js/jquery.treemenu.js' %}"></script>
        <script>
        $(function(){
                $(".tree").treemenu({delay:300}).openActive();
            });
        </script>
        <!-- mtree script to left category menu-->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/velocity/0.2.1/jquery.velocity.min.js'></script>
        <script src="{% static '/js/mtree.js'%}"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="{% static 'js/mtree_search_category.js' %}"></script>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        
          ga('create', 'UA-88596207-2', 'auto');
          ga('send', 'pageview');
        
        </script>
        {% block script_extra %}

        {% endblock script_extra %}
    </body>
</html>

templates/message_display.html
{% if messages %}
    <div class="alert alert-success" role="alert">
        <ul class="messages">
            {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/pagination.html
{% load post_tags %}
<div class="pagination">
    <span class="step-links">
        <ul class="pager">
        {% if page.has_previous %}
            <li><a href="?{% url_replace request 'page' page.previous_page_number %}">Poprzednia</a></li>
        {% endif %}
        <span class="current">
            {{ page.number }} z {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <li><a href="?{% url_replace request 'page' page.next_page_number %}">Nastepna</a></li>
        {% endif %}
        </ul>
    </span>
</div>

templates/tree_view.html
<ul class="fordtreeview mtree transit">
    <li class=""><input type="text" class="form-control menufilter" placeholder="Search..."/></li>
    {%for category in categories %}
        {%include "tree_view_template.html" %}
    {%endfor%}
    <hr/>
    <div class="no-checkedselector">
        <div class="toggle-container">
            <input id="toggle-on" class="toggle toggle-left" name="toggle" type="radio" checked>
            <label for="toggle-on" class="btn">On</label>
            <input id="toggle-off" class="toggle toggle-right" name="toggle" type="radio">
            <label for="toggle-off" class="btn">Off</label>
            <label class="deep-label">Deep Search</label>
        </div>
    </div>
</ul>

templates/tree_view_template.html
<li> <span class="hasSub">
{#    <a href="{{ category.get_absolute_url }}?deep_search=on" class="fa fa-shield fa-flip-horizontal" style="font-size: 8px" aria-hidden="true"> </a>#}
    <a onclick="deepSearchClickLink(this)" href="{{ category.get_absolute_url }}" id="{{ category.id }}">{{ category.name }}</a>
    </span>
    {%if category.children.count > 0 %}
        <ul>
         {%for ch in category.children.all %}
              {%with category=ch template_name="tree_view_template.html" %}
                   {%include template_name%}
              {%endwith%}
         {%endfor%}
         </ul>
    {%endif%}
</li>